# -*- coding: utf-8 -*-
"""kel 5(jam belajar siswa).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cPB8xJRE7_W34kOwlTd7kKQ2tVPotUXY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df = pd.read_csv('score.csv')
df

df.head()

df.info()

df.describe()

import matplotlib.pyplot as plt

x = df["Hours"].values
x

y = df["Scores"].values
y

plt.scatter(x,y)
plt.xlabel("Number of study hours")
plt.ylabel("Score")
plt.title("relation between study hours & Score")
plt.plot

X = x.reshape(-1,1)
X

from sklearn.model_selection import train_test_split
x_train, x_test,  y_train, y_test = train_test_split(X,y, test_size=.2, train_size=.8)

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr.fit(x_train, y_train)

y_predicted = lr.predict(x_test)
y_predicted

lr.score(x_test,y_test) * 100

plt.scatter(x_test,y_test)
plt.plot(x_test, y_predicted)
plt.xlabel("Number of study hours")
plt.ylabel("Scores")
plt.title("relation between study hours & Score")
plt.plot